[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config", "vips"]

[phases.install]
cmds = ["npm install --build-from-source", "cd client && npm install && npm run build"]

[start]
cmd = "node server/index.js"
