const express = require('express');
const { getListingsForItem, updateListing, getItem, getListing } = require('../db/queries');
const { checkManualListing } = require('../scrapers/manual');

const router = express.Router();

// Get listings for an item
router.get('/item/:itemId', (req, res) => {
  try {
    const status = req.query.status || null;
    const listings = getListingsForItem(parseInt(req.params.itemId, 10), status);
    res.json(listings);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Manual listing check (paste a listing)
router.post('/check', async (req, res) => {
  try {
    const { item_id, url, title, description, images } = req.body;
    const item = getItem(item_id);
    if (!item) return res.status(404).json({ error: 'Item not found' });

    const result = await checkManualListing(item, { url, title, description, images });
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Generate DMCA / fraud report template (eBay-oriented)
router.get('/:id/dmca', (req, res) => {
  try {
    const listing = getListing(parseInt(req.params.id, 10));
    if (!listing) return res.status(404).json({ error: 'Listing not found' });

    const item = getItem(listing.item_id);
    const itemDesc = item ? (item.description || item.name) : '';

    const template = `DMCA / Stolen Property Report (template)

Platform: ${listing.platform}
Listing URL: ${listing.url || 'N/A'}
Listing title: ${listing.title || 'N/A'}
Observed price: ${listing.price || 'N/A'}

I am reporting that the above listing may offer stolen property that belongs to me.

Description of my property:
${itemDesc}

This item was stolen on [DATE] from [LOCATION]. I have registered this case in RecoverWatch and believe this listing may match my stolen item based on my records and AI-assisted review (see RecoverWatch case notes).

A police report has been filed: [POLICE REPORT NUMBER]

I request that this listing be reviewed, removed if appropriate, and that seller information be preserved for law enforcement.

Sincerely,
[YOUR NAME]
[EMAIL] [PHONE]

---
Generated by RecoverWatch. Edit bracketed fields before submitting through the platform's reporting flow.
`;

    res.json({ template });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Update listing status (reviewed/dismissed)
router.put('/:id', (req, res) => {
  try {
    const { status, match_score } = req.body;
    updateListing(parseInt(req.params.id, 10), { status, match_score });
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
