const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function absUpload(rel) {
  return path.join(__dirname, '..', '..', rel);
}

function writeCaseFilePdf(res, item, listings) {
  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="recoverwatch-case-${item.id}.pdf"`
  );
  doc.pipe(res);

  doc.fontSize(20).text('RecoverWatch — Case file', { underline: true });
  doc.moveDown();
  doc.fontSize(11).text(`Generated: ${new Date().toISOString()}`, { align: 'right' });
  doc.moveDown(2);

  doc.fontSize(14).text('Registered item', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(11);
  doc.text(`Name: ${item.name || '—'}`);
  doc.text(`Category: ${item.category || '—'}`);
  doc.text(`City / scan target: ${item.city || '—'}`);
  doc.text(`Status: ${item.status || 'watching'}`);
  doc.moveDown();
  doc.text('Description:');
  doc.text(item.description || '—', { align: 'left' });
  doc.moveDown();

  const prof = item.structured_profile || {};
  doc.text('Structured profile (JSON):');
  doc.fontSize(9).text(JSON.stringify(prof, null, 2), { align: 'left' });
  doc.fontSize(11);
  doc.moveDown();

  if (item.photos && item.photos.length > 0) {
    doc.text('Reference photos:', { underline: true });
    doc.moveDown(0.5);
    for (const p of item.photos.slice(0, 6)) {
      const ap = absUpload(p);
      if (fs.existsSync(ap)) {
        try {
          doc.image(ap, { width: 200 });
          doc.moveDown();
        } catch {
          doc.text(`(Could not embed image: ${p})`);
        }
      } else {
        doc.text(`(Missing file: ${p})`);
      }
    }
    doc.moveDown();
  }

  doc.addPage();
  doc.fontSize(14).text('Flagged & tracked listings', { underline: true });
  doc.moveDown();

  if (!listings.length) {
    doc.fontSize(11).text('No listings recorded for this item.');
  }

  listings.forEach((listing, i) => {
    doc.fontSize(12).text(`Listing ${i + 1}`, { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10);
    doc.text(`Platform: ${listing.platform}`);
    doc.text(`Match score: ${listing.match_score}`);
    doc.text(`Flagged at: ${listing.flagged_at || '—'}`);
    doc.text(`Title: ${listing.title || '—'}`);
    doc.text(`Price: ${listing.price || '—'}`);
    doc.text(`Location: ${listing.location || '—'}`);
    doc.text(`URL: ${listing.url || '—'}`);
    doc.moveDown(0.3);
    let analysis = listing.ai_analysis;
    if (typeof analysis === 'string') {
      try {
        analysis = JSON.parse(analysis);
      } catch {
        /* keep */
      }
    }
    doc.text('AI analysis:');
    const text =
      typeof analysis === 'object' && analysis !== null
        ? JSON.stringify(analysis, null, 2)
        : String(analysis || '—');
    doc.fontSize(9).text(text, { align: 'left' });
    doc.fontSize(10);
    doc.moveDown(0.5);
    if (listing.images && listing.images[0]) {
      const ip = absUpload(listing.images[0]);
      if (fs.existsSync(ip)) {
        try {
          doc.image(ip, { width: 160 });
        } catch {
          doc.text('(thumbnail unavailable)');
        }
      }
    }
    doc.moveDown(1.5);
    if (doc.y > 650) doc.addPage();
  });

  doc.fontSize(8).text(
    'This report was generated by RecoverWatch for use with law enforcement or insurance. Verify all URLs independently.',
    50,
    doc.page.height - 60,
    { align: 'center', width: doc.page.width - 100 }
  );

  doc.end();
}

module.exports = { writeCaseFilePdf };
